name: prof. marques teixeira
favicon: null
layout_spectrum: 0.41692
typography_spectrum: 0.5496634379960597
title: prof. marques teixeira
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4c4958'
    - '#d8ae4f'
    - '#ad446a'
    - '#ffd5db'
  brandStrength: 0.375
  lightness: 0.41224422468803823
  saturation: 0.6537210387177765
  rhythmicContrast: 0.631654460914433
purpose: []
